// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PayRight.Conta.Infra.Contexts;

#nullable disable

namespace PayRight.Conta.Infra.Migrations
{
    [DbContext(typeof(ContextoDbEscrita))]
    [Migration("20220111174408_PrimeiroMigrate")]
    partial class PrimeiroMigrate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PayRight.Conta.Domain.Entities.ContaCorrente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("Saldo")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(13, 2)
                        .HasColumnType("decimal(13,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("UltimaAtualizacaoEm")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ultima_alteracao");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("idx_usuario_id");

                    b.ToTable("contas_correntes", (string)null);
                });

            modelBuilder.Entity("PayRight.Conta.Domain.Entities.ContaCorrente", b =>
                {
                    b.OwnsOne("PayRight.Conta.Domain.ValueObjects.NomeConta", "NomeConta", b1 =>
                        {
                            b1.Property<Guid>("ContaCorrenteId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Apelido")
                                .HasMaxLength(15)
                                .HasColumnType("varchar(15)")
                                .HasColumnName("apelido");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasMaxLength(24)
                                .HasColumnType("varchar(24)")
                                .HasColumnName("nome");

                            b1.HasKey("ContaCorrenteId");

                            b1.ToTable("contas_correntes");

                            b1.WithOwner()
                                .HasForeignKey("ContaCorrenteId");
                        });

                    b.Navigation("NomeConta")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
