name: Development Pipeline

on: [ pull_request ]
    
env:
  DOTNET6_VERSION: '6.0.x'

jobs:
  check-code-build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          ref: ${{ GITHUB.HEAD_REF }}

#      - name: 'Running Horusec'
#        run: |
#            curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
#            horusec start -p="./src/" -e="true"
      - name: Source Branch Name
        run:  echo ${{ GITHUB.HEAD_REF }}
        
      - name: Setup .NET ${{ env.DOTNET6_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET6_VERSION }}
        
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore
        
      - name: Test
        run: dotnet test --no-build --verbosity normal
